### ISSUE TITLE
More posts link doesn't work

### ISSUE THREAD

**Issue by DealsBeam** [nagahitoyuki/imaginary-liquid#2]
https://steamgamebundles.blogspot.com/ the "More posts" link at the bottom doesn't work

Also, the Facebook and Twitter buttons doesn't work

**Comment by nagahitoyuki** [comment]
I am sorry.
An error occurred in the program when the first blog search widget was not used.
I fixed it.
Please download the template file again.

**Comment by DealsBeam** [comment]
Thank you, are you able to improve the performance for mobile? https://web.dev/measure/

**Comment by nagahitoyuki** [comment]
You use AdSense ads in your blog, right? They significantly reduce blog performance. 

If you really want to improve performance white using AdSense ads, you need lazy loading of them.

I don't recommend it because there is a risk of violating AdSense policy. Though lazy loading doesn't help with auto ads, it has a huge effect on others.

Regarding auto ads, I think it is generally good to reduce them to the minimum number without putting them at the top of the the blog.

**Comment by DealsBeam** [comment]
Thanks for the reply, would it be possible if you could modernize the Awesome Inc. theme on blogspot and release your own version?

**Comment by nagahitoyuki** [comment]
I don't advice about lazy loading of AdSense ads because of this reason: https://support.google.com/adsense/thread/45264685/lazy-loading-on-adsense-ads?hl=en&msgid=45264685

It may be done in this way: https://www.gulshankumar.net/setup-lazy-loading-google-adsense-ad-units/

If you have any questions, please ask another person.

I don't do lazy loading of AdSense ads and prefer to use them more safely.
